/* Copyright (C) 2011-2015 Zeex
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

[native] int CreateActor(int modelid, float x, float y, float z, float rotation);
[native] bool DestroyActor(int actorid);
[native] bool IsActorStreamedIn(int actorid, int forplayerid);

[native] bool SetActorVirtualWorld(int actorid, int vworld);
[native] int GetActorVirtualWorld(int actorid);

[native] bool ApplyActorAnimation(int actorid, string animlib, string animname, float fDelta, bool loop, bool lockx, bool locky, bool freeze, int time);
[native] bool ClearActorAnimations(int actorid);

[native] bool SetActorPos(int actorid, float x, float y, float z);
[native] bool GetActorPos(int actorid, [out] float x, [out] float y, [out] float z);
[native] bool SetActorFacingAngle(int actorid, float angle);
[native] bool GetActorFacingAngle(int actorid, [out] float angle);

[native] bool SetActorHealth(int actorid, float health);
[native] bool GetActorHealth(int actorid, [out] float health);
[native] bool SetActorInvulnerable(int actorid, bool invulnerable = true);
[native] bool IsActorInvulnerable(int actorid);

[native] bool IsValidActor(int actorid);
