/* Copyright (C) 2011-2015 Zeex
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const int MAX_PLAYER_NAME       = 24;
const int MAX_CLIENT_MESSAGE    = 144;
const int MAX_PLAYERS           = 1000;
const int MAX_VEHICLES          = 2000;
const int MAX_ACTORS            = 1000;
const int INVALID_PLAYER_ID     = 0xFFFF;
const int INVALID_VEHICLE_ID    = 0xFFFF;
const int INVALID_ACTOR_ID      = 0xFFFF;
const int NO_TEAM               = 255;
const int MAX_OBJECTS           = 1000;
const int INVALID_OBJECT_ID     = 0xFFFF;
const int MAX_GANG_ZONES        = 1024;
const int MAX_TEXT_DRAWS        = 2048;
const int MAX_PLAYER_TEXT_DRAWS = 256;
const int MAX_MENUS             = 128;
const int MAX_3DTEXT_GLOBAL     = 1024;
const int MAX_3DTEXT_PLAYER     = 1024;
const int MAX_PICKUPS           = 4096;
const int INVALID_MENU          = 0xFF;
const int INVALID_TEXT_DRAW     = 0xFFFF;
const int INVALID_GANG_ZONE     = -1;
const int INVALID_3DTEXT_ID     = 0xFFFF;

[native] bool SendClientMessage(int playerid, int color, string message);
[native] bool SendClientMessageToAll(int color, string message);
[native] bool SendPlayerMessageToPlayer(int playerid, int senderid, string message);
[native] bool SendPlayerMessageToAll(int senderid, string message);
[native] bool SendDeathMessage(int killer, int killee, int weapon);
[native] bool SendDeathMessageToPlayer(int playerid, int killer, int killee, int weapon);
[native] bool GameTextForAll(string text, int time, int style);
[native] bool GameTextForPlayer(int playerid, string text, int time, int style);
[native] int GetTickCount();
[native] int GetMaxPlayers();
[native] float VectorSize(float x, float y, float z);
[native] int GetPlayerPoolSize();
[native] int GetVehiclePoolSize();
[native] int GetActorPoolSize();

[native] bool SHA256_PassHash(string password, string salt, [out] string ret_hash, int ret_hash_len);

[native] bool SetSVarInt(string varname, int int_value);
[native] int GetSVarInt(string varname);
[native] bool SetSVarString(string varname, string string_value);
[native] bool GetSVarString(string varname, [out] string string_return, int len);
[native] bool SetSVarFloat(string varname, float float_value);
[native] float GetSVarFloat(string varname);
[native] bool DeleteSVar(string varname);

const int SERVER_VARTYPE_NONE = 0;
const int SERVER_VARTYPE_INT = 1;
const int SERVER_VARTYPE_STRING = 2;
const int SERVER_VARTYPE_FLOAT = 3;

[native] int GetSVarsUpperIndex();
[native] bool GetSVarNameAtIndex(int index, [out] string ret_varname, int ret_len);
[native] int GetSVarType(string varname);

[native] bool SetGameModeText(string text);
[native] bool SetTeamCount(int count);
[native] int AddPlayerClass(int modelid, float spawn_x, float spawn_y, float spawn_z, float z_angle, int weapon1, int weapon1_ammo, int weapon2, int weapon2_ammo, int weapon3, int weapon3_ammo);
[native] int AddPlayerClassEx(int teamid, int modelid, float spawn_x, float spawn_y, float spawn_z, float z_angle, int weapon1, int weapon1_ammo, int weapon2, int weapon2_ammo, int weapon3, int weapon3_ammo);
[native] int AddStaticVehicle(int modelid, float spawn_x, float spawn_y, float spawn_z, float z_angle, int color1, int color2);
[native] int AddStaticVehicleEx(int modelid, float spawn_x, float spawn_y, float spawn_z, float z_angle, int color1, int color2, int respawn_delay, bool addsiren = false);
[native] int AddStaticPickup(int model, int type, float x, float y, float z, int virtualworld = 0);
[native] int CreatePickup(int model, int type, float x, float y, float z, int virtualworld = 0);
[native] bool DestroyPickup(int pickup);
[native] bool ShowNameTags(bool show);
[native] bool ShowPlayerMarkers(int mode);
[native] bool GameModeExit();
[native] bool SetWorldTime(int hour);
[native] bool GetWeaponName(int weaponid, [out] string name, int size);
[native] bool EnableTirePopping(bool enable);
[native] bool EnableVehicleFriendlyFire();
[native] bool AllowInteriorWeapons(bool allow);
[native] bool SetWeather(int weatherid);
[native] bool SetGravity(float gravity);
[native] float GetGravity();
[native] bool AllowAdminTeleport(bool allow);
[native] bool SetDeathDropAmount(int amount);
[native] bool CreateExplosion(float x, float y, float z, int type, float radius);
[native] bool EnableZoneNames(bool enable);
[native] bool UsePlayerPedAnims();
[native] bool DisableInteriorEnterExits();
[native] bool SetNameTagDrawDistance(float distance);
[native] bool DisableNameTagLOS();
[native] bool LimitGlobalChatRadius(float chat_radius);
[native] bool LimitPlayerMarkerRadius(float marker_radius);

[native] bool ConnectNPC(string name, string script);
[native] bool IsPlayerNPC(int playerid);

[native] bool IsPlayerAdmin(int playerid);
[native] bool Kick(int playerid);
[native] bool Ban(int playerid);
[native] bool BanEx(int playerid, string reason);
[native] bool SendRconCommand(string command);
[native] bool GetPlayerNetworkStats(int playerid, [out] string retstr, int size);
[native] bool GetNetworkStats([out] string retstr, int size);
[native] bool GetPlayerVersion(int playerid, [out] string version, int len);
[native] bool BlockIpAddress(string ip_address, int timems);
[native] bool UnBlockIpAddress(string ip_address);

[native] bool GetServerVarAsString(string varname, [out] string value, int size);
[native] int GetServerVarAsInt(string varname);
[native] bool GetServerVarAsBool(string varname);
[native] bool GetConsoleVarAsString(string varname, [out] string buffer, int len);
[native] int GetConsoleVarAsInt(string varname);
[native] bool GetConsoleVarAsBool(string varname);

[native] int GetServerTickRate();
[native] int NetStats_GetConnectedTime(int playerid);
[native] int NetStats_MessagesReceived(int playerid);
[native] int NetStats_BytesReceived(int playerid);
[native] int NetStats_MessagesSent(int playerid);
[native] int NetStats_BytesSent(int playerid);
[native] int NetStats_MessagesRecvPerSecond(int playerid);
[native] float NetStats_PacketLossPercent(int playerid);
[native] int NetStats_ConnectionStatus(int playerid);
[native] bool NetStats_GetIpPort(int playerid, [out] string ip_port, int ip_port_len);

[native] int CreateMenu(string title, int columns, float x, float y, float col1width, float col2width = 0.0);
[native] bool DestroyMenu(int menuid);
[native] int AddMenuItem(int menuid, int column, string menutext);
[native] bool SetMenuColumnHeader(int menuid, int column, string columnheader);
[native] bool ShowMenuForPlayer(int menuid, int playerid);
[native] bool HideMenuForPlayer(int menuid, int playerid);
[native] bool IsValidMenu(int menuid);
[native] bool DisableMenu(int menuid);
[native] bool DisableMenuRow(int menuid, int row);
[native] int GetPlayerMenu(int playerid);

const int TEXT_DRAW_FONT_SPRITE_DRAW   = 4;
const int TEXT_DRAW_FONT_MODEL_PREVIEW = 5;

[native] int TextDrawCreate(float x, float y, string text);
[native] bool TextDrawDestroy(int text);
[native] bool TextDrawLetterSize(int text, float x, float y);
[native] bool TextDrawTextSize(int text, float x, float y);
[native] bool TextDrawAlignment(int text, int alignment);
[native] bool TextDrawColor(int text, int color);
[native] bool TextDrawUseBox(int text, bool use);
[native] bool TextDrawBoxColor(int text, int color);
[native] bool TextDrawSetShadow(int text, int size);
[native] bool TextDrawSetOutline(int text, int size);
[native] bool TextDrawBackgroundColor(int text, int color);
[native] bool TextDrawFont(int text, int font);
[native] bool TextDrawSetProportional(int text, bool set);
[native] bool TextDrawSetSelectable(int text, bool set);
[native] bool TextDrawShowForPlayer(int playerid, int text);
[native] bool TextDrawHideForPlayer(int playerid, int text);
[native] bool TextDrawShowForAll(int text);
[native] bool TextDrawHideForAll(int text);
[native] bool TextDrawSetString(int text, string string);
[native] bool TextDrawSetPreviewModel(int text, int modelindex);
[native] bool TextDrawSetPreviewRot(int text, float fRotX, float fRotY, float fRotZ, float fZoom = 1.0);
[native] bool TextDrawSetPreviewVehCol(int text, int color1, int color2);

[native] bool SelectTextDraw(int playerid, int hovercolor);
[native] bool CancelSelectTextDraw(int playerid);

[native] int GangZoneCreate(float minx, float miny, float maxx, float maxy);
[native] bool GangZoneDestroy(int zone);
[native] bool GangZoneShowForPlayer(int playerid, int zone, int color);
[native] bool GangZoneShowForAll(int zone, int color);
[native] bool GangZoneHideForPlayer(int playerid, int zone);
[native] bool GangZoneHideForAll(int zone);
[native] bool GangZoneFlashForPlayer(int playerid, int zone, int flashcolor);
[native] bool GangZoneFlashForAll(int zone, int flashcolor);
[native] bool GangZoneStopFlashForPlayer(int playerid, int zone);
[native] bool GangZoneStopFlashForAll(int zone);

[native] int Create3DTextLabel(string text, int color, float x, float y, float z, float DrawDistance, int virtualworld, bool testLOS = false);
[native] bool Delete3DTextLabel(int id);
[native] bool Attach3DTextLabelToPlayer(int id, int playerid, float OffsetX, float OffsetY, float OffsetZ);
[native] bool Attach3DTextLabelToVehicle(int id, int vehicleid, float OffsetX, float OffsetY, float OffsetZ);
[native] bool Update3DTextLabelText(int id, int color, string text);

[native] int CreatePlayer3DTextLabel(int playerid, string text, int color, float x, float y, float z, float DrawDistance, int attachedplayer = INVALID_PLAYER_ID, int attachedvehicle = INVALID_VEHICLE_ID, bool testLOS = false);
[native] bool DeletePlayer3DTextLabel(int playerid, int id);
[native] bool UpdatePlayer3DTextLabelText(int playerid, int id, int color, string text);

const int DIALOG_STYLE_MSGBOX          = 0;
const int DIALOG_STYLE_INPUT           = 1;
const int DIALOG_STYLE_LIST            = 2;
const int DIALOG_STYLE_PASSWORD        = 3;
const int DIALOG_STYLE_TABLIST         = 4;
const int DIALOG_STYLE_TABLIST_HEADERS = 5;

[native] bool ShowPlayerDialog(int playerid, int dialogid, int style, string caption, string info, string button1, string button2);

[native, noimpl] int SetTimer(int interval, bool repeat, TimerCallback callback, [in, out] void param);
[native, noimpl] bool KillTimer(int timerid);

const int PLAYER_STATE_NONE                    = 0;
const int PLAYER_STATE_ONFOOT                  = 1;
const int PLAYER_STATE_DRIVER                  = 2;
const int PLAYER_STATE_PASSENGER               = 3;
const int PLAYER_STATE_EXIT_VEHICLE            = 4;
const int PLAYER_STATE_ENTER_VEHICLE_DRIVER    = 5;
const int PLAYER_STATE_ENTER_VEHICLE_PASSENGER = 6;
const int PLAYER_STATE_WASTED                  = 7;
const int PLAYER_STATE_SPAWNED                 = 8;
const int PLAYER_STATE_SPECTATING              = 9;

const int PLAYER_MARKERS_MODE_OFF              = 0;
const int PLAYER_MARKERS_MODE_GLOBAL           = 1;
const int PLAYER_MARKERS_MODE_STREAMED         = 2;

const int WEAPON_FIST             = 0;
const int WEAPON_BRASSKNUCKLE     = 1;
const int WEAPON_GOLFCLUB         = 2;
const int WEAPON_NITESTICK        = 3;
const int WEAPON_KNIFE            = 4;
const int WEAPON_BAT              = 5;
const int WEAPON_SHOVEL           = 6;
const int WEAPON_POOLSTICK        = 7;
const int WEAPON_KATANA           = 8;
const int WEAPON_CHAINSAW         = 9;
const int WEAPON_DILDO            = 10;
const int WEAPON_DILDO2           = 11;
const int WEAPON_VIBRATOR         = 12;
const int WEAPON_VIBRATOR2        = 13;
const int WEAPON_FLOWER           = 14;
const int WEAPON_CANE             = 15;
const int WEAPON_GRENADE          = 16;
const int WEAPON_TEARGAS          = 17;
const int WEAPON_MOLTOV           = 18;
const int WEAPON_COLT45           = 22;
const int WEAPON_SILENCED         = 23;
const int WEAPON_DEAGLE           = 24;
const int WEAPON_SHOTGUN          = 25;
const int WEAPON_SAWEDOFF         = 26;
const int WEAPON_SHOTGSPA         = 27;
const int WEAPON_UZI              = 28;
const int WEAPON_MP5              = 29;
const int WEAPON_AK47             = 30;
const int WEAPON_M4               = 31;
const int WEAPON_TEC9             = 32;
const int WEAPON_RIFLE            = 33;
const int WEAPON_SNIPER           = 34;
const int WEAPON_ROCKETLAUNCHER   = 35;
const int WEAPON_HEATSEEKER       = 36;
const int WEAPON_FLAMETHROWER     = 37;
const int WEAPON_MINIGUN          = 38;
const int WEAPON_SATCHEL          = 39;
const int WEAPON_BOMB             = 40;
const int WEAPON_SPRAYCAN         = 41;
const int WEAPON_FIREEXTINGUISHER = 42;
const int WEAPON_CAMERA           = 43;
const int WEAPON_NIGHTVISION      = 44;
const int WEAPON_INFRARED         = 45;
const int WEAPON_PARACHUTE        = 46;
const int WEAPON_VEHICLE          = 49;
const int WEAPON_DROWN            = 53;
const int WEAPON_COLLISION        = 54;

const int VEHICLE_LANDSTALKER        = 400;
const int VEHICLE_BRAVURA            = 401;
const int VEHICLE_BUFFALO            = 402;
const int VEHICLE_LINERUNNER         = 403;
const int VEHICLE_PERRENIAL          = 404;
const int VEHICLE_SENTINEL           = 405;
const int VEHICLE_DUMPER             = 406;
const int VEHICLE_FIRETRUCK          = 407;
const int VEHICLE_TRASHMASTER        = 408;
const int VEHICLE_STRETCH            = 409;
const int VEHICLE_MANANA             = 410;
const int VEHICLE_INFERNUS           = 411;
const int VEHICLE_VOODOO             = 412;
const int VEHICLE_PONY               = 413;
const int VEHICLE_MULE               = 414;
const int VEHICLE_CHEETAH            = 415;
const int VEHICLE_AMBULANCE          = 416;
const int VEHICLE_LEVIATHAN          = 417;
const int VEHICLE_MOONBEAM           = 418;
const int VEHICLE_ESPERANTO          = 419;
const int VEHICLE_TAXI               = 420;
const int VEHICLE_WASHINGTON         = 421;
const int VEHICLE_BOBCAT             = 422;
const int VEHICLE_MRWHOOPEE          = 423;
const int VEHICLE_BFINJECTION        = 424;
const int VEHICLE_HUNTER             = 425;
const int VEHICLE_PREMIER            = 426;
const int VEHICLE_ENFORCER           = 427;
const int VEHICLE_SECURICAR          = 428;
const int VEHICLE_BANSHEE            = 429;
const int VEHICLE_PREDATOR           = 430;
const int VEHICLE_BUS                = 431;
const int VEHICLE_RHINO              = 432;
const int VEHICLE_BARRACKS           = 433;
const int VEHICLE_HOTKNIFE           = 434;
const int VEHICLE_ARTICLETRAILER1    = 435;
const int VEHICLE_PREVION            = 436;
const int VEHICLE_COACH              = 437;
const int VEHICLE_CABBIE             = 438;
const int VEHICLE_STALLION           = 439;
const int VEHICLE_RUMPO              = 440;
const int VEHICLE_RCBANDIT           = 441;
const int VEHICLE_ROMERO             = 442;
const int VEHICLE_PACKER             = 443;
const int VEHICLE_MONSTER            = 444;
const int VEHICLE_ADMIRAL            = 445;
const int VEHICLE_SQUALO             = 446;
const int VEHICLE_SEASPARROW         = 447;
const int VEHICLE_PIZZABOY           = 448;
const int VEHICLE_TRAM               = 449;
const int VEHICLE_ARTICLETRAILER2    = 450;
const int VEHICLE_TURISMO            = 451;
const int VEHICLE_SPEEDER            = 452;
const int VEHICLE_REEFER             = 453;
const int VEHICLE_TROPIC             = 454;
const int VEHICLE_FLATBED            = 455;
const int VEHICLE_YANKEE             = 456;
const int VEHICLE_CADDY              = 457;
const int VEHICLE_SOLAIR             = 458;
const int VEHICLE_BERKLEYSRCVAN      = 459;
const int VEHICLE_SKIMMER            = 460;
const int VEHICLE_PCJ600             = 461;
const int VEHICLE_FAGGIO             = 462;
const int VEHICLE_FREEWAY            = 463;
const int VEHICLE_RCBARON            = 464;
const int VEHICLE_RCRAIDER           = 465;
const int VEHICLE_GLENDALE           = 466;
const int VEHICLE_OCEANIC            = 467;
const int VEHICLE_SANCHEZ            = 468;
const int VEHICLE_SPARROW            = 469;
const int VEHICLE_PATRIOT            = 470;
const int VEHICLE_QUAD               = 471;
const int VEHICLE_COASTGUARD         = 472;
const int VEHICLE_DINGHY             = 473;
const int VEHICLE_HERMES             = 474;
const int VEHICLE_SABRE              = 475;
const int VEHICLE_RUSTLER            = 476;
const int VEHICLE_ZR350              = 477;
const int VEHICLE_WALTON             = 478;
const int VEHICLE_REGINA             = 479;
const int VEHICLE_COMET              = 480;
const int VEHICLE_BMX                = 481;
const int VEHICLE_BURRITO            = 482;
const int VEHICLE_CAMPER             = 483;
const int VEHICLE_MARQUIS            = 484;
const int VEHICLE_BAGGAGE            = 485;
const int VEHICLE_DOZER              = 486;
const int VEHICLE_MAVERICK           = 487;
const int VEHICLE_SANNEWSMAVERICK    = 488;
const int VEHICLE_RANCHER            = 489;
const int VEHICLE_FBIRANCHER         = 490;
const int VEHICLE_VIRGO              = 491;
const int VEHICLE_GREENWOOD          = 492;
const int VEHICLE_JETMAX             = 493;
const int VEHICLE_HOTRINGRACER       = 494;
const int VEHICLE_SANDKING           = 495;
const int VEHICLE_BLISTACOMPACT      = 496;
const int VEHICLE_POLICEMAVERICK     = 497;
const int VEHICLE_BOXVILLE           = 498;
const int VEHICLE_BENSON             = 499;
const int VEHICLE_MESA               = 500;
const int VEHICLE_RCGOBLIN           = 501;
const int VEHICLE_HOTRINGRACERA      = 502;
const int VEHICLE_HOTRINGRACERB      = 503;
const int VEHICLE_BLOODRINGBANGER    = 504;
const int VEHICLE_RANCHERLURE        = 505;
const int VEHICLE_SUPERGT            = 506;
const int VEHICLE_ELEGANT            = 507;
const int VEHICLE_JOURNEY            = 508;
const int VEHICLE_BIKE               = 509;
const int VEHICLE_MOUNTAINBIKE       = 510;
const int VEHICLE_BEAGLE             = 511;
const int VEHICLE_CROPDUST           = 512;
const int VEHICLE_STUNTPLANE         = 513;
const int VEHICLE_TANKER             = 514;
const int VEHICLE_ROADTRAIN          = 515;
const int VEHICLE_NEBULA             = 516;
const int VEHICLE_MAJESTIC           = 517;
const int VEHICLE_BUCCANEER          = 518;
const int VEHICLE_SHAMAL             = 519;
const int VEHICLE_HYDRA              = 520;
const int VEHICLE_FCR900             = 521;
const int VEHICLE_NRG500             = 522;
const int VEHICLE_HPV1000            = 523;
const int VEHICLE_CEMENTTRUCK        = 524;
const int VEHICLE_TOWTRUCK           = 525;
const int VEHICLE_FORTUNE            = 526;
const int VEHICLE_CADRONA            = 527;
const int VEHICLE_FBITRUCK           = 528;
const int VEHICLE_WILLARD            = 529;
const int VEHICLE_FORKLIFT           = 530;
const int VEHICLE_TRACTOR            = 531;
const int VEHICLE_COMBINE            = 532;
const int VEHICLE_FELTZER            = 533;
const int VEHICLE_REMINGTON          = 534;
const int VEHICLE_SLAMVAN            = 535;
const int VEHICLE_BLADE              = 536;
const int VEHICLE_FREIGHT            = 537;
const int VEHICLE_BROWNSTREAK        = 538;
const int VEHICLE_VORTEX             = 539;
const int VEHICLE_VINCENT            = 540;
const int VEHICLE_BULLET             = 541;
const int VEHICLE_CLOVER             = 542;
const int VEHICLE_SADLER             = 543;
const int VEHICLE_FIRETRUCKLA        = 544;
const int VEHICLE_HUSTLER            = 545;
const int VEHICLE_INTRUDER           = 546;
const int VEHICLE_PRIMO              = 547;
const int VEHICLE_CARGOBOB           = 548;
const int VEHICLE_TAMPA              = 549;
const int VEHICLE_SUNRISE            = 550;
const int VEHICLE_MERIT              = 551;
const int VEHICLE_UTILITYVAN         = 552;
const int VEHICLE_NEVADA             = 553;
const int VEHICLE_YOSEMITE           = 554;
const int VEHICLE_WINDSOR            = 555;
const int VEHICLE_MONSTERA           = 556;
const int VEHICLE_MONSTERB           = 557;
const int VEHICLE_URANUS             = 558;
const int VEHICLE_JESTER             = 559;
const int VEHICLE_SULTAN             = 560;
const int VEHICLE_STRATUM            = 561;
const int VEHICLE_ELEGY              = 562;
const int VEHICLE_RAINDANCE          = 563;
const int VEHICLE_RCTIGER            = 564;
const int VEHICLE_FLASH              = 565;
const int VEHICLE_TAHOMA             = 566;
const int VEHICLE_SAVANNA            = 567;
const int VEHICLE_BANDITO            = 568;
const int VEHICLE_FREIGHTFLATTRAILER = 569;
const int VEHICLE_STREAKTRAILER      = 570;
const int VEHICLE_KART               = 571;
const int VEHICLE_MOWER              = 572;
const int VEHICLE_DUNERIDE           = 573;
const int VEHICLE_SWEEPER            = 574;
const int VEHICLE_BROADWAY           = 575;
const int VEHICLE_TORNADO            = 576;
const int VEHICLE_AT400              = 577;
const int VEHICLE_DFT30              = 578;
const int VEHICLE_HUNTLEY            = 579;
const int VEHICLE_STAFFORD           = 580;
const int VEHICLE_BF400              = 581;
const int VEHICLE_NEWSVAN            = 582;
const int VEHICLE_TUG                = 583;
const int VEHICLE_PETROLTRAILER      = 584;
const int VEHICLE_EMPEROR            = 585;
const int VEHICLE_WAYFARER           = 586;
const int VEHICLE_EUROS              = 587;
const int VEHICLE_HOTDOG             = 588;
const int VEHICLE_CLUB               = 589;
const int VEHICLE_FREIGHTBOXTRAILER  = 590;
const int VEHICLE_ARTICLETRAILER3    = 591;
const int VEHICLE_ANDROMADA          = 592;
const int VEHICLE_DODO               = 593;
const int VEHICLE_RCCAM              = 594;
const int VEHICLE_LAUNCH             = 595;
const int VEHICLE_POLICECARLSPD      = 596;
const int VEHICLE_POLICECARSFPD      = 597;
const int VEHICLE_POLICECARLVPD      = 598;
const int VEHICLE_POLICERANGER       = 599;
const int VEHICLE_PICADOR            = 600;
const int VEHICLE_SWAT               = 601;
const int VEHICLE_ALPHA              = 602;
const int VEHICLE_PHOENIX            = 603;
const int VEHICLE_GLENDALESHIT       = 604;
const int VEHICLE_SADLERSHIT         = 605;
const int VEHICLE_BAGGAGETRAILERA    = 606;
const int VEHICLE_BAGGAGETRAILERB    = 607;
const int VEHICLE_TUGSTAIRSTRAILER   = 608;
const int VEHICLE_BOXBURG            = 609;
const int VEHICLE_FARMTRAILER        = 610;
const int VEHICLE_UTILITYTRAILER     = 611;

const int KEY_ACTION           = 1;
const int KEY_CROUCH           = 2;
const int KEY_FIRE             = 4;
const int KEY_SPRINT           = 8;
const int KEY_SECONDARY_ATTACK = 16;
const int KEY_JUMP             = 32;
const int KEY_LOOK_RIGHT       = 64;
const int KEY_HANDBRAKE        = 128;
const int KEY_LOOK_LEFT        = 256;
const int KEY_SUBMISSION       = 512;
const int KEY_LOOK_BEHIND      = 512;
const int KEY_WALK             = 1024;
const int KEY_ANALOG_UP        = 2048;
const int KEY_ANALOG_DOWN      = 4096;
const int KEY_ANALOG_LEFT      = 8192;
const int KEY_ANALOG_RIGHT     = 16384;
const int KEY_YES              = 65536;
const int KEY_NO               = 131072;
const int KEY_CTRL_BACK        = 262144;
const int KEY_UP               = -128;
const int KEY_DOWN             = 128;
const int KEY_LEFT             = -128;
const int KEY_RIGHT            = 128;

const int BODY_PART_TORSO = 3;
const int BODY_PART_GROIN = 4;
const int BODY_PART_LEFT_ARM = 5;
const int BODY_PART_RIGHT_ARM = 6;
const int BODY_PART_LEFT_LEG = 7;
const int BODY_PART_RIGHT_LEG = 8;
const int BODY_PART_HEAD = 9;

[native] bool gpci(int playerid, [out] string buffer, int size);

[callback] bool OnGameModeInit();
[callback] bool OnGameModeExit();
[callback, badret(false)] bool OnPlayerConnect(int playerid);
[callback, badret(false)] bool OnPlayerDisconnect(int playerid, int reason);
[callback, badret(false)] bool OnPlayerSpawn(int playerid);
[callback, badret(false)] bool OnPlayerDeath(int playerid, int killerid, int reason);
[callback, badret(false)] bool OnVehicleSpawn(int vehicleid);
[callback] bool OnVehicleDeath(int vehicleid, int killerid);
[callback, badret(false)] bool OnPlayerText(int playerid, string text);
[callback, badret(true)] bool OnPlayerCommandText(int playerid, string cmdtext);
[callback] bool OnPlayerRequestClass(int playerid, int classid);
[callback] bool OnPlayerEnterVehicle(int playerid, int vehicleid, bool ispassenger);
[callback] bool OnPlayerExitVehicle(int playerid, int vehicleid);
[callback] bool OnPlayerStateChange(int playerid, int newstate, int oldstate);
[callback] bool OnPlayerEnterCheckpoint(int playerid);
[callback] bool OnPlayerLeaveCheckpoint(int playerid);
[callback] bool OnPlayerEnterRaceCheckpoint(int playerid);
[callback] bool OnPlayerLeaveRaceCheckpoint(int playerid);
[callback, badret(true)] bool OnRconCommand(string cmd);
[callback, badret(false)] bool OnPlayerRequestSpawn(int playerid);
[callback] bool OnObjectMoved(int objectid);
[callback] bool OnPlayerObjectMoved(int playerid, int objectid);
[callback] bool OnPlayerPickUpPickup(int playerid, int pickupid);
[callback, badret(false)] bool OnVehicleMod(int playerid, int vehicleid, int componentid);
[callback] bool OnEnterExitModShop(int playerid, bool enterexit, int interiorid);
[callback, badret(false)] bool OnVehiclePaintjob(int playerid, int vehicleid, int paintjobid);
[callback, badref(false)] bool OnVehicleRespray(int playerid, int vehicleid, int color1, int color2);
[callback, badret(true)] bool OnVehicleDamageStatusUpdate(int vehicleid, int playerid);
[callback, badret(false)] bool OnUnoccupiedVehicleUpdate(int vehicleid, int playerid, int passenger_seat, float new_x, float new_y, float new_z, float vel_x, float vel_y, float vel_z);
[callback] bool OnPlayerSelectedMenuRow(int playerid, int row);
[callback] bool OnPlayerExitedMenu(int playerid);
[callback] bool OnPlayerInteriorChange(int playerid, int newinteriorid, int oldinteriorid);
[callback] bool OnPlayerKeyStateChange(int playerid, int newkeys, int oldkeys);
[callback] bool OnRconLoginAttempt(string ip, string password, bool success);
[callback, badret(false)] bool OnPlayerUpdate(int playerid);
[callback] bool OnPlayerStreamIn(int playerid, int forplayerid);
[callback] bool OnPlayerStreamOut(int playerid, int forplayerid);
[callback] bool OnVehicleStreamIn(int vehicleid, int forplayerid);
[callback] bool OnVehicleStreamOut(int vehicleid, int forplayerid);
[callback] bool OnActorStreamIn(int actorid, int forplayerid);
[callback] bool OnActorStreamOut(int actorid, int forplayerid);
[callback, badret(true)] bool OnDialogResponse(int playerid, int dialogid, int response, int listitem, string inputtext);
[callback, badret(true)] bool OnPlayerTakeDamage(int playerid, int issuerid, float amount, int weaponid, int bodypart);
[callback, badret(true)] bool OnPlayerGiveDamage(int playerid, int damagedid, float amount, int weaponid, int bodypart);
[callback, badret(true)] bool OnPlayerGiveDamageActor(int playerid, int damaged_actorid, float amount, int weaponid, int bodypart);
[callback, badret(true)] bool OnPlayerClickMap(int playerid, float fX, float fY, float fZ);
[callback, badret(true)] bool OnPlayerClickTextDraw(int playerid, int clickedid);
[callback, badret(true)] bool OnPlayerClickPlayerTextDraw(int playerid, int playertextid);
[callback, badret(true)] bool OnIncomingConnection(int playerid, string ip_address, int port);
[callback, badret(false)] bool OnTrailerUpdate(int playerid, int vehicleid);
[callback] bool OnVehicleSirenStateChange(int playerid, int vehicleid, int newstate);

const int CLICK_SOURCE_SCOREBOARD = 0;

[callback, badret(true)] bool OnPlayerClickPlayer(int playerid, int clickedplayerid, int source);

const int EDIT_RESPONSE_CANCEL = 0;
const int EDIT_RESPONSE_FINAL  = 1;
const int EDIT_RESPONSE_UPDATE = 2;

[callback, badret(true)] bool OnPlayerEditObject(int playerid, bool playerobject, int objectid, int response, float fX, float fY, float fZ, float fRotX, float fRotY, float fRotZ);
[callback, badret(true)] bool OnPlayerEditAttachedObject(int playerid, int response, int index, int modelid, int boneid, float fOffsetX, float fOffsetY, float fOffsetZ, float fRotX, float fRotY, float fRotZ, float fScaleX, float fScaleY, float fScaleZ);

const int SELECT_OBJECT_GLOBAL_OBJECT = 1;
const int SELECT_OBJECT_PLAYER_OBJECT = 2;

[callback, badret(true)] bool OnPlayerSelectObject(int playerid, int type, int objectid, int modelid, float fX, float fY, float fZ);

const int BULLET_HIT_TYPE_NONE          = 0;
const int BULLET_HIT_TYPE_PLAYER        = 1;
const int BULLET_HIT_TYPE_VEHICLE       = 2;
const int BULLET_HIT_TYPE_OBJECT        = 3;
const int BULLET_HIT_TYPE_PLAYER_OBJECT = 4;

[callback, badret(false)] bool OnPlayerWeaponShot(int playerid, int weaponid, int hittype, int hitid, float fX, float fY, float fZ);
